"""重构Lens模型，引入基础模型LensBase

Revision ID: 1b0eaceeb196
Revises: 9bfa6cbc188a
Create Date: 2025-07-12 11:12:46.320264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b0eaceeb196'
down_revision: Union[str, None] = '9bfa6cbc188a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lens_ibfk_3', 'lens', type_='foreignkey')
    op.drop_column('lens', 'mount_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lens', sa.Column('mount_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('lens_ibfk_3', 'lens', 'mount', ['mount_id'], ['id'])
    # ### end Alembic commands ###
