"""添加品牌卡口多对多表

Revision ID: d3f45d0b3a0b
Revises: f9a0c4ccce3d
Create Date: 2025-05-12 23:00:29.054035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3f45d0b3a0b'
down_revision: Union[str, None] = 'f9a0c4ccce3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brandmountlink',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['mount_id'], ['mount.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'mount_id')
    )
    op.drop_constraint('mount_ibfk_1', 'mount', type_='foreignkey')
    op.drop_column('mount', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mount', sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mount_ibfk_1', 'mount', 'brand', ['brand_id'], ['id'])
    op.drop_table('brandmountlink')
    # ### end Alembic commands ###
